apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  type: LoadBalancer
  ports:
  - port: 8181
    targetPort: 8181
  selector:
    app: api-gateway
    version: blue # This can be changed to "green" when switching traffic