apiVersion: v1
kind: Service
metadata:
  name: coupon-service
spec:
  type: ClusterIP
  ports:
  - port: 8001
  selector:
    app: coupon-app
    version: blue # This can be changed to "green" when switching traffic