apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
      version: blue
  template:
    metadata:
      labels: 
        app: eureka-server
        version: blue
    spec:
      containers:
      - name: eureka-server
        image: guravarchies/eureka-server:blue 
        ports: 
        - containerPort: 8761
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "1000Mi"
            cpu: "1000m"