apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  type: ClusterIP
  ports:
  - port: 8002
  selector:
    app: inventory-app
    version: blue # This can be changed to "green" when switching traffic