server:
  port: 8002

spring:
  application:
    name: inventory-service

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI}

management:
  endpoints:
    web:
      exposure:
        include: "*"